name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
      with:
        nix_path: nixpkgs=channel:nixos-20.03
    - uses: cachix/cachix-action@v6
      with:
        name: basile-henry
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
